name: ZipPluginLoader
main: ZipPluginLoader\Main
version: [2.0.0, 2.1.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2]
api: 2.0.0
load: STARTUP
author: aliuly
description: Load Zip packed plugins
website: https://github.com/Muirfield/ZipPluginLoader
